# Generated by Django 5.0.4 on 2024-05-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
