"""
Django settings for expensetracker project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment detection
# Set ENVIRONMENT variable to 'local', 'railway', 'pythonanywhere', or 'seenode'
# Defaults to 'local' if not set
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'local')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-4wp46j4_r5(4v_3&jp2m-68j$p9ny)qylj%_(&n^k^q9xz&jn%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Environment-specific settings
if ENVIRONMENT == 'local':
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
elif ENVIRONMENT == 'railway':
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')
    if not ALLOWED_HOSTS or ALLOWED_HOSTS == ['']:
        ALLOWED_HOSTS = ['*']  # Fallback for Railway
elif ENVIRONMENT == 'seenode':
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')
    if not ALLOWED_HOSTS or ALLOWED_HOSTS == ['']:
        ALLOWED_HOSTS = ['*']  # Fallback for Seenode
elif ENVIRONMENT == 'pythonanywhere':
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'unkerpaulie.pythonanywhere.com').split(',')
else:
    ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "core",
    "expenses",
    "income",
    "authentication",
    "preferences",
    "reports",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]

# Add WhiteNoise for Railway and Seenode (static file serving)
if ENVIRONMENT in ['railway', 'seenode']:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')

MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'expensetracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'expensetracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if ENVIRONMENT == 'local':
    # Local development uses SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif ENVIRONMENT == 'railway':
    # Railway uses PostgreSQL via DATABASE_URL
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif ENVIRONMENT == 'seenode':
    # Seenode uses PostgreSQL via DATABASE_URL or individual parameters
    database_url = os.environ.get('DATABASE_URL')

    if database_url:
        # Use DATABASE_URL if provided
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.config(
                default=database_url,
                conn_max_age=600,
                ssl_require=True,
            )
        }
    else:
        # Fallback to individual parameters
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.environ.get('DB_NAME', ''),
                'USER': os.environ.get('DB_USER', ''),
                'PASSWORD': os.environ.get('DB_PASSWORD', ''),
                'HOST': os.environ.get('DB_HOST', ''),
                'PORT': os.environ.get('DB_PORT', '5432'),
                'OPTIONS': {
                    'sslmode': 'require',
                },
            }
        }
elif ENVIRONMENT == 'pythonanywhere':
    # PythonAnywhere can use either SQLite or MySQL
    # Check if DATABASE_URL is provided, otherwise use SQLite
    database_url = os.environ.get('DATABASE_URL')
    if database_url:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.config(
                default=database_url,
                conn_max_age=600,
            )
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # Fallback to SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

if ENVIRONMENT == 'local':
    # Local development doesn't need STATIC_ROOT
    pass
elif ENVIRONMENT in ['railway', 'seenode']:
    # Railway and Seenode need STATIC_ROOT for WhiteNoise
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    # WhiteNoise configuration for Railway and Seenode
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
elif ENVIRONMENT == 'pythonanywhere':
    # PythonAnywhere needs STATIC_ROOT
    STATIC_ROOT = BASE_DIR / 'static'
else:
    STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/auth/login'
# LOGIN_REDIRECT_URL = ''

# CSRF Trusted Origins - environment specific
if ENVIRONMENT == 'railway':
    railway_url = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
    if railway_url:
        CSRF_TRUSTED_ORIGINS = [f'https://{railway_url}']
    else:
        # Fallback to your specific Railway domain
        CSRF_TRUSTED_ORIGINS = ['https://expensetracker-production-b92e.up.railway.app']
elif ENVIRONMENT == 'seenode':
    seenode_url = os.environ.get('SEENODE_DOMAIN', '')
    if seenode_url:
        CSRF_TRUSTED_ORIGINS = [f'https://{seenode_url}']
    else:
        # Will be set via environment variable
        CSRF_TRUSTED_ORIGINS = []
elif ENVIRONMENT == 'pythonanywhere':
    pythonanywhere_url = os.environ.get('PYTHONANYWHERE_DOMAIN', 'unkerpaulie.pythonanywhere.com')
    CSRF_TRUSTED_ORIGINS = [f'https://{pythonanywhere_url}']
else:
    CSRF_TRUSTED_ORIGINS = []
