# Generated by Django 5.0.4 on 2024-05-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-income_date'], 'verbose_name_plural': 'Income'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name']},
        ),
    ]
