# Generated by Django 5.0.4 on 2024-05-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_rename_category_income_source'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='source',
            table='income_source',
        ),
    ]
